"""LLVM module extension.

Detects a system LLVM install via `llvm-config` and exposes it as an external
repository `@llvm//` with a single `cc_library //:llvm` target carrying:

  - `includes`  pointing at LLVM's include dir (symlinked into the repo),
  - `linkopts`  pulled from `llvm-config --libs core orcjit native --system-libs`,
                plus `-L<libdir>` and `-Wl,-rpath,<libdir>` so the linked
                binary can find the LLVM dylib at runtime.

Detection precedence:
  1. `LLVM_CONFIG` env var (overrides everything).
  2. `which llvm-config` on `PATH`.
  3. Hardcoded fallbacks: Homebrew (arm64 + x86_64), Debian/Ubuntu apt.

This is a local repository — Bazel will re-run the rule whenever the
`LLVM_CONFIG` or `PATH` env vars change.
"""

_FALLBACK_PATHS = [
    "/opt/homebrew/opt/llvm/bin/llvm-config",
    "/usr/local/opt/llvm/bin/llvm-config",
    "/usr/bin/llvm-config",
]

def _find_llvm_config(rctx):
    env_val = rctx.os.environ.get("LLVM_CONFIG", "")
    if env_val:
        return env_val
    wc = rctx.execute(["which", "llvm-config"])
    if wc.return_code == 0 and wc.stdout.strip():
        return wc.stdout.strip()
    for c in _FALLBACK_PATHS:
        tr = rctx.execute(["test", "-x", c])
        if tr.return_code == 0:
            return c
    return ""

def _llvm_repo_impl(rctx):
    llvm_config = _find_llvm_config(rctx)
    if not llvm_config:
        fail(
            "llvm-config not found. Install LLVM " +
            "(brew install llvm / apt install llvm-dev), " +
            "or set the LLVM_CONFIG env var.",
        )

    def run(args, what):
        result = rctx.execute([llvm_config] + args)
        if result.return_code != 0:
            fail("llvm-config {} failed (rc={}): {}".format(
                what,
                result.return_code,
                result.stderr,
            ))
        return result.stdout.strip()

    version = run(["--version"], "--version")
    include_dir = run(["--includedir"], "--includedir")
    lib_dir = run(["--libdir"], "--libdir")
    libs_out = run(["--libs", "core", "orcjit", "native"], "--libs")
    syslibs_out = run(["--system-libs"], "--system-libs")

    # Assemble link options. Pass `-L<libdir>` + rpath up front, then everything
    # `llvm-config` emits as -l / -pthread / absolute-path / -framework <name>.
    # NOTE: Starlark's str.split() requires an explicit separator (unlike Python),
    # so normalize tabs/newlines to spaces and filter empty splits manually.
    linkopts = ["-L" + lib_dir, "-Wl,-rpath," + lib_dir]
    raw = libs_out + " " + syslibs_out
    for ws in ["\t", "\n", "\r"]:
        raw = raw.replace(ws, " ")
    toks = [t for t in raw.split(" ") if t]
    pending_framework = False
    for t in toks:
        if pending_framework:
            linkopts.append(t)
            pending_framework = False
            continue
        if t == "-framework":
            linkopts.append(t)
            pending_framework = True
        elif t.startswith("-l") or t == "-pthread" or t.startswith("/"):
            linkopts.append(t)

    # Symlink the system include tree into the external repo so a glob can
    # cover the headers and Bazel's sandbox lets the compiler read them.
    rctx.symlink(include_dir, "include")

    build_content = """# Auto-generated by //bazel/llvm:extension.bzl. DO NOT EDIT.
# Regenerated whenever the LLVM repo rule re-runs (LLVM_CONFIG/PATH change).

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "llvm",
    hdrs = glob(["include/**"], allow_empty = True),
    includes = ["include"],
    linkopts = {linkopts},
)
""".format(linkopts = repr(linkopts))

    rctx.file("BUILD.bazel", build_content)
    print("kardashev: detected LLVM {} at {}".format(version, llvm_config))

_llvm_repo = repository_rule(
    implementation = _llvm_repo_impl,
    environ = ["LLVM_CONFIG", "PATH"],
    local = True,
)

def _llvm_extension_impl(ctx):
    _llvm_repo(name = "llvm")

llvm_extension = module_extension(
    implementation = _llvm_extension_impl,
)
