//! Project scaffolding (`kard init`): create a new project directory with a
//! `build.kd` and a hello-world `src/main.kd`, in the spirit of `zig init`.
//!
//! Layout produced:
//!
//! ```text
//! <dir>/
//!   build.kd        # the v1 minimal build manifest (SPEC §7)
//!   README.md
//!   src/
//!     main.kd       # a runnable Gen-2 hello-world (SPEC §2)
//! ```

use std::fs;
use std::io;
use std::path::Path;

/// Scaffold a new project named `name` rooted at `dir`.
///
/// Creates `dir` (and `dir/src`) if needed, then writes `build.kd`,
/// `src/main.kd` and `README.md`. If `dir` already exists and is **non-empty**,
/// nothing is written and an [`io::ErrorKind::AlreadyExists`] error is returned,
/// so an existing project is never clobbered.
pub fn init_project(dir: &Path, name: &str) -> io::Result<()> {
    // Refuse to overwrite an existing, non-empty directory.
    if dir.exists() {
        let mut entries = fs::read_dir(dir)?;
        if entries.next().is_some() {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                format!(
                    "`{}` already exists and is not empty; refusing to scaffold over it",
                    dir.display()
                ),
            ));
        }
    }

    let src_dir = dir.join("src");
    fs::create_dir_all(&src_dir)?;

    fs::write(dir.join("build.kd"), build_kd(name))?;
    fs::write(src_dir.join("main.kd"), main_kd())?;
    fs::write(dir.join("README.md"), readme_md(name))?;

    Ok(())
}

/// Render the minimal `build.kd` manifest for `name` (SPEC §7).
fn build_kd(name: &str) -> String {
    format!(
        "build {{\n    name = \"{}\";\n    root = \"src/main.kd\";\n}}\n",
        escape_kd_string(name)
    )
}

/// A runnable Gen-2 hello-world. Exercises a `var`, a `while` loop, a `defer`,
/// `print(...)` and an `i32` `return` — every construct here is valid per
/// SPEC §2/§3 and the `main` return type (`i32`) is accepted by the driver.
fn main_kd() -> String {
    // Note: assignment is a statement, not an expression, so the loop counter
    // is advanced in the body rather than in a `while (...) : (...)` clause.
    "// Generated by `kard init`.\n\
     //\n\
     // Build and run with `kard run`.\n\
     pub fn main() i32 {\n\
     \x20   var i: i32 = 0;\n\
     \x20   defer print(0);\n\
     \x20   while (i < 3) {\n\
     \x20       print(i);\n\
     \x20       i = i + 1;\n\
     \x20   }\n\
     \x20   return 0;\n\
     }\n"
        .to_string()
}

/// Render the project README.
fn readme_md(name: &str) -> String {
    format!(
        "# {name}\n\
         \n\
         A new [kardashev](https://github.com/) project.\n\
         \n\
         ## Build & run\n\
         \n\
         ```sh\n\
         kard build      # compile to a native executable\n\
         kard run        # build and run\n\
         kard test       # build and run the test harness\n\
         ```\n\
         \n\
         The build is described in `build.kd`; the program entrypoint is\n\
         `src/main.kd`.\n",
        name = name
    )
}

/// Escape a string for embedding inside a `build.kd` double-quoted literal.
/// Mirrors the lexer's escapes (`\\` and `\"`); other characters pass through.
fn escape_kd_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    /// A unique, not-yet-created path inside the OS temp directory.
    fn unique_temp_path(tag: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        std::env::temp_dir().join(format!("kardashev_scaffold_{}_{}_{}", tag, std::process::id(), nanos))
    }

    /// Run `f` with a fresh temp path, always cleaning it up afterwards.
    fn with_temp<F: FnOnce(&Path)>(tag: &str, f: F) {
        let dir = unique_temp_path(tag);
        let _ = fs::remove_dir_all(&dir);
        f(&dir);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn creates_the_full_project_layout() {
        with_temp("layout", |dir| {
            init_project(dir, "demo").expect("init should succeed");

            let build = dir.join("build.kd");
            let main = dir.join("src").join("main.kd");
            let readme = dir.join("README.md");

            assert!(build.exists(), "build.kd should exist");
            assert!(main.exists(), "src/main.kd should exist");
            assert!(readme.exists(), "README.md should exist");

            let build_txt = fs::read_to_string(&build).unwrap();
            assert!(build_txt.contains("name = \"demo\""), "build.kd has the name");
            assert!(build_txt.contains("root = \"src/main.kd\""), "build.kd has the root");

            let main_txt = fs::read_to_string(&main).unwrap();
            assert!(main_txt.contains("fn main"), "main.kd defines main");
            assert!(main_txt.contains("print("), "main.kd calls print");
            assert!(main_txt.contains("return 0"), "main.kd returns 0");

            let readme_txt = fs::read_to_string(&readme).unwrap();
            assert!(readme_txt.contains("demo"), "README mentions the project name");
        });
    }

    #[test]
    fn generated_build_kd_round_trips_through_the_parser() {
        with_temp("roundtrip", |dir| {
            init_project(dir, "roundtrip-demo").expect("init should succeed");
            let build_txt = fs::read_to_string(dir.join("build.kd")).unwrap();
            let spec = crate::build_system::parse_build_kd(&build_txt)
                .expect("generated build.kd should parse");
            assert_eq!(spec.name, "roundtrip-demo");
            assert_eq!(spec.root, "src/main.kd");
        });
    }

    #[test]
    fn refuses_to_overwrite_a_non_empty_directory() {
        with_temp("nonempty", |dir| {
            fs::create_dir_all(dir).unwrap();
            fs::write(dir.join("existing.txt"), b"keep me").unwrap();

            let err = init_project(dir, "x").expect_err("should refuse");
            assert_eq!(err.kind(), io::ErrorKind::AlreadyExists);

            // The pre-existing file must be untouched.
            assert_eq!(fs::read_to_string(dir.join("existing.txt")).unwrap(), "keep me");
            assert!(!dir.join("build.kd").exists(), "no build.kd was written");
        });
    }

    #[test]
    fn succeeds_into_an_existing_empty_directory() {
        with_temp("empty", |dir| {
            fs::create_dir_all(dir).unwrap();
            init_project(dir, "into-empty").expect("empty dir is fine");
            assert!(dir.join("build.kd").exists());
        });
    }
}
